const pizzaBranches = [
  {
    branch_id: "1",
    branch_name: "אום אל פאחם",
    district: "חיפה",
    openTime: "10:30",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branch_id: "2",
    branch_name: "אופקים",
    district: "דרום",
    openTime: "10:30",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "3",
    branch_name: "אור עקיבא",
    district: "חיפה",
    openTime: "10:00",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branch_id: "4",
    branch_name: "אילת - טיילת",
    district: "דרום",
    openTime: "09:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "5",
    branch_name: "איילת -הרים",
    district: "דרום",
    openTime: "10:00",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branch_id: "6",
    branch_name: "אילת - קניון אדום",
    district: "דרום",
    openTime: "10:30",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "7",
    branch_name: "אשדוד",
    district: "דרום",
    openTime: "09:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "8",
    branch_name: "אשקלון",
    district: "דרום",
    openTime: "11:00",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branch_id: "9",
    branch_name: "באקה אל גרבייה",
    district: "מרכז",
    openTime: "11:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "10",
    branch_name: "באר שבע - רמות",
    district: "דרום",
    openTime: "09:30",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branch_id: "11",
    branch_name: "באר שבע - קניון",
    district: "דרום",
    openTime: "09:00",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branch_id: "12",
    branch_name: "באר שבע - אביסרור",
    district: "דרום",
    openTime: "10:00",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branch_id: "13",
    branch_name: "בילו סנטר",
    district: "מרכז",
    openTime: "10:30",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "14",
    branch_name: "בית שאן",
    district: "צפון",
    openTime: "10:30",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "15",
    branch_name: "בית שמש",
    district: "מרכז",
    openTime: "11:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "16",
    branch_name: "בני ברק",
    district: "דן",
    openTime: "10:30",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branch_id: "18",
    branch_name: "בת ים",
    district: "דן",
    openTime: "11:00",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branch_id: "19",
    branch_name: "גבעת שמואל",
    district: "דן",
    openTime: "09:30",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branch_id: "20",
    branch_name: "גדרה",
    district: "מרכז",
    openTime: "10:30",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "21",
    branch_name: "קרית אונו",
    district: "דן",
    openTime: "11:00",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branch_id: "22",
    branch_name: "בני דרור",
    district: "דן",
    openTime: "10:30",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branch_id: "23",
    branch_name: "דלית אל כרמל",
    district: "חיפה",
    openTime: "09:30",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "24",
    branch_name: "דימונה",
    district: "דרום",
    openTime: "10:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "25",
    branch_name: "הוד השרון",
    district: "דן",
    openTime: "09:00",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branch_id: "26",
    branch_name: "זכרון יעקב",
    district: "חיפה",
    openTime: "09:00",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branch_id: "27",
    branch_name: "הרצליה",
    district: "דן",
    openTime: "10:00",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branch_id: "28",
    branch_name: "חדרה",
    district: "חיפה",
    openTime: "09:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "29",
    branch_name: "חולון מזרח",
    district: "דן",
    openTime: "11:00",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branch_id: "30",
    branch_name: "חולון מערב",
    district: "דן",
    openTime: "09:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "31",
    branch_name: "חיפה - טכניון",
    district: "חיפה",
    openTime: "10:30",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branch_id: "32",
    branch_name: "חיפה - מוריה",
    district: "חיפה",
    openTime: "09:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "33",
    branch_name: "חיפה - מושבה גרמנית",
    district: "חיפה",
    openTime: "09:00",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branch_id: "34",
    branch_name: "חריש",
    district: "חיפה",
    openTime: "10:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "35",
    branch_name: "טבריה",
    district: "צפון",
    openTime: "10:30",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branch_id: "36",
    branch_name: "טייבה",
    district: "מרכז",
    openTime: "10:00",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branch_id: "37",
    branch_name: "טירה",
    district: "מרכז",
    openTime: "09:30",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branch_id: "38",
    branch_name: "יבנה",
    district: "מרכז",
    openTime: "09:00",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branch_id: "39",
    branch_name: "יהוד",
    district: "מרכז",
    openTime: "11:00",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branch_id: "40",
    branch_name: "יקנעם",
    district: "חיפה",
    openTime: "10:00",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branch_id: "41",
    branch_name: "ירושלים - בית הלל",
    district: "מרכז",
    openTime: "10:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "42",
    branch_name: "ירושלים - מלחה",
    district: "מרכז",
    openTime: "09:30",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "43",
    branch_name: "ירושלים - ניות",
    district: "מרכז",
    openTime: "09:00",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branch_id: "44",
    branch_name: "ירושלים - פסגת זאב",
    district: "מרכז",
    openTime: "10:30",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "45",
    branch_name: "ירושלים - רמות",
    district: "מרכז",
    openTime: "11:00",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branch_id: "46",
    branch_name: "ירושלים - שועפט",
    district: "מרכז",
    openTime: "10:30",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branch_id: "47",
    branch_name: "ירושלים - תחנה מרכזית",
    district: "מרכז",
    openTime: "10:30",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "48",
    branch_name: "ירקה",
    district: "צפון",
    openTime: "09:30",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branch_id: "49",
    branch_name: "כפר יסעיף",
    district: "צפון",
    openTime: "09:30",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branch_id: "50",
    branch_name: "כפר יונה",
    district: "מרכז",
    openTime: "09:30",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branch_id: "51",
    branch_name: "כפר מרר",
    district: "צפון",
    openTime: "11:00",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branch_id: "52",
    branch_name: "כפר סבא",
    district: "מרכז",
    openTime: "10:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "53",
    branch_name: "כפר קסם",
    district: "מרכז",
    openTime: "10:30",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "54",
    branch_name: "כפר קרע",
    district: "חיפה",
    openTime: "09:00",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branch_id: "55",
    branch_name: "כרמיאל",
    district: "צפון",
    openTime: "09:30",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branch_id: "56",
    branch_name: "כרמיאל - אקספרס",
    district: "צפון",
    openTime: "09:00",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branch_id: "57",
    branch_name: "מבשרת ציון",
    district: "מרכז",
    openTime: "09:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "58",
    branch_name: "מגדל",
    district: "צפון",
    openTime: "10:00",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branch_id: "59",
    branch_name: "גבעתיים",
    district: "דן",
    openTime: "10:00",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branch_id: "60",
    branch_name: "מודיעין",
    district: "מרכז",
    openTime: "09:00",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branch_id: "61",
    branch_name: "מעלה אדומים",
    district: "מרכז",
    openTime: "09:00",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branch_id: "61",
    branch_name: "מעלות",
    district: "צפון",
    openTime: "09:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "62",
    branch_name: "מצפה רמון",
    district: "דרום",
    openTime: "10:00",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branch_id: "63",
    branch_name: "נהריה",
    district: "צפון",
    openTime: "09:30",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branch_id: "64",
    branch_name: "נס ציונה",
    district: "מרכז",
    openTime: "10:30",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branch_id: "65",
    branch_name: "נצרת",
    district: "חיפה",
    openTime: "09:00",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branch_id: "66",
    branch_name: "נטיבות",
    district: "דרום",
    openTime: "11:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "67",
    branch_name: "נתניה - מרכז העיר",
    district: "מרכז",
    openTime: "11:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "68",
    branch_name: "נתניה - פולג",
    district: "מרכז",
    openTime: "10:30",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "69",
    branch_name: "סכנין",
    district: "צפון",
    openTime: "10:00",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branch_id: "70",
    branch_name: "עכו",
    district: "צפון",
    openTime: "10:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "71",
    branch_name: "עפולה",
    district: "צפון",
    openTime: "09:30",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branch_id: "72",
    branch_name: "ערד",
    district: "דרום",
    openTime: "11:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "73",
    branch_name: "פארק אדיסון",
    district: "צפון",
    openTime: "09:30",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branch_id: "74",
    branch_name: "רמת גן - מרום נווה",
    district: "דן",
    openTime: "10:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "75",
    branch_name: "רמת גן - קניון ביאליק",
    district: "דן",
    openTime: "10:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "76",
    branch_name: "פרדס חנה",
    district: "חיפה",
    openTime: "10:00",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branch_id: "77",
    branch_name: "פתח תקווה - אם המושבות",
    district: "דן",
    openTime: "10:30",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branch_id: "78",
    branch_name: "פתח תקווה - בלינסון",
    district: "דן",
    openTime: "11:00",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branch_id: "79",
    branch_name: "פתח תקווה כפר - גנים",
    district: "דן",
    openTime: "09:00",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branch_id: "80",
    branch_name: "פתח תקווה - סירקין",
    district: "דן",
    openTime: "09:30",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branch_id: "81",
    branch_name: "קרית מוצקין",
    district: "חיפה",
    openTime: "10:30",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branch_id: "82",
    branch_name: "קרית אתא",
    district: "חיפה",
    openTime: "10:00",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branch_id: "83",
    branch_name: "קרית גת",
    district: "דרום",
    openTime: "10:30",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "82",
    branch_name: "ירושלים - קרית יובל",
    district: "מרכז",
    openTime: "09:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "83",
    branch_name: "קרית - שמונה",
    district: "צפון",
    openTime: "09:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "84",
    branch_name: "ראש העין",
    district: "דן",
    openTime: "10:30",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "85",
    branch_name: "ראש פינה",
    district: "צפון",
    openTime: "10:30",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branch_id: "86",
    branch_name: "ראשון לציון - מזרח",
    district: "מרכז",
    openTime: "11:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "87",
    branch_name: "ראשון לציון - מערב",
    district: "מרכז",
    openTime: "10:30",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "88",
    branch_name: "רהט",
    district: "דרום",
    openTime: "10:00",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branch_id: "89",
    branch_name: "רחובות",
    district: "מרכז",
    openTime: "11:00",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branch_id: "90",
    branch_name: "רמת השרון",
    district: "דן",
    openTime: "10:00",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branch_id: "91",
    branch_name: "רמלה לוד",
    district: "מרכז",
    openTime: "10:30",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "92",
    branch_name: "רמת ישי",
    district: "חיפה",
    openTime: "09:00",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branch_id: "93",
    branch_name: "רעננה",
    district: "מרכז",
    openTime: "10:30",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "94",
    branch_name: "שדרות",
    district: "דרום",
    openTime: "09:30",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branch_id: "95",
    branch_name: "שוהם",
    district: "מרכז",
    openTime: "11:00",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branch_id: "96",
    branch_name: "שפרעם - קניון האחים סמרה",
    district: "חיפה",
    openTime: "09:30",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branch_id: "97",
    branch_name: "תל אביב - יד אליהו",
    district: "דן",
    openTime: "10:00",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branch_id: "98",
    branch_name: "תל אביב - רמת החייל",
    district: "דן",
    openTime: "09:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "99",
    branch_name: "תל אביב - חשמונאים",
    district: "דן",
    openTime: "09:30",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branch_id: "100",
    branch_name: "תל אביב - רמת אביב",
    district: "דן",
    openTime: "09:30",
    closeTime: "22:30",
    branchOpen: "Open",
  },
];

const pizzaMapId = {
  "אום אל פאחם": "1",
  אופקים: "2",
  "אור עקיבא": "3",
  "אילת - טיילת": "4",
  "איילת -הרים": "5",
  "אילת - קניון אדום": "6",
  אשדוד: "7",
  אשקלון: "8",
  "באקה אל גרבייה": "9",
  "באר שבע - רמות": "10",
  "באר שבע - קניון": "11",
  "באר שבע - אביסרור": "12",
  "בילו סנטר": "13",
  "בית שאן": "14",
  "בית שמש": "15",
  "בני ברק": "16",
  "בת ים": "18",
  "גבעת שמואל": "19",
  גדרה: "20",
  "קרית אונו": "21",
  "בני דרור": "22",
  "דלית אל כרמל": "23",
  דימונה: "24",
  "הוד השרון": "25",
  "זכרון יעקב": "26",
  הרצליה: "27",
  חדרה: "28",
  "חולון מזרח": "29",
  "חולון מערב": "30",
  "חיפה - טכניון": "31",
  "חיפה - מוריה": "32",
  "חיפה - מושבה גרמנית": "33",
  חריש: "34",
  טבריה: "35",
  טייבה: "36",
  טירה: "37",
  יבנה: "38",
  יהוד: "39",
  יקנעם: "40",
  "ירושלים - בית הלל": "41",
  "ירושלים - מלחה": "42",
  "ירושלים - ניות": "43",
  "ירושלים - פסגת זאב": "44",
  "ירושלים - רמות": "45",
  "ירושלים - שועפט": "46",
  "ירושלים - תחנה מרכזית": "47",
  ירקה: "48",
  "כפר יסעיף": "49",
  "כפר יונה": "50",
  "כפר מרר": "51",
  "כפר סבא": "52",
  "כפר קסם": "53",
  "כפר קרע": "54",
  כרמיאל: "55",
  "כרמיאל - אקספרס": "56",
  "מבשרת ציון": "57",
  מגדל: "58",
  גבעתיים: "59",
  מודיעין: "60",
  "מעלה אדומים": "61",
  מעלות: "61",
  "מצפה רמון": "62",
  נהריה: "63",
  "נס ציונה": "64",
  נצרת: "65",
  נטיבות: "66",
  "נתניה - מרכז העיר": "67",
  "נתניה - פולג": "68",
  סכנין: "69",
  עכו: "70",
  עפולה: "71",
  ערד: "72",
  "פארק אדיסון": "73",
  "רמת גן - מרום נווה": "74",
  "רמת גן - קניון ביאליק": "75",
  "פרדס חנה": "76",
  "פתח תקווה - אם המושבות": "77",
  "פתח תקווה - בלינסון": "78",
  "פתח תקווה כפר - גנים": "79",
  "פתח תקווה - סירקין": "80",
  "קרית מוצקין": "81",
  "קרית אתא": "82",
  "קרית גת": "83",
  "ירושלים - קרית יובל": "82",
  "קרית - שמונה": "83",
  "ראש העין": "84",
  "ראש פינה": "85",
  "ראשון לציון - מזרח": "86",
  "ראשון לציון - מערב": "87",
  רהט: "88",
  רחובות: "89",
  "רמת השרון": "90",
  "רמלה לוד": "91",
  "רמת ישי": "92",
  רעננה: "93",
  שדרות: "94",
  שוהם: "95",
  "שפרעם - קניון האחים סמרה": "96",
  "תל אביב - יד אליהו": "97",
  "תל אביב - רמת החייל": "98",
  "תל אביב - חשמונאים": "99",
  "תל אביב - רמת אביב": "100",
};

const pizzaTopping = ["onion", "olives", "tomato", "corn", "mushrooms"];

module.exports = {
  pizzaTopping,
  pizzaBranches,
  pizzaMapId,
};
