export const pizzaBranches = [
  {
    branchId: "1",
    branchName: "אום אל פאחם",
    district: "Haifa",
    openTime: "10:30",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branchId: "2",
    branchName: "אופקים",
    district: "South",
    openTime: "10:30",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "3",
    branchName: "אור עקיבא",
    district: "Haifa",
    openTime: "10:00",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branchId: "4",
    branchName: "אילת - טיילת",
    district: "South",
    openTime: "09:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "5",
    branchName: "איילת -הרים",
    district: "South",
    openTime: "10:00",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branchId: "6",
    branchName: "אילת - קניון אדום",
    district: "South",
    openTime: "10:30",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "7",
    branchName: "אשדוד",
    district: "South",
    openTime: "09:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "8",
    branchName: "אשקלון",
    district: "South",
    openTime: "11:00",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branchId: "9",
    branchName: "באקה אל גרבייה",
    district: "Center",
    openTime: "11:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "10",
    branchName: "באר שבע - רמות",
    district: "South",
    openTime: "09:30",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branchId: "11",
    branchName: "באר שבע - קניון",
    district: "South",
    openTime: "09:00",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branchId: "12",
    branchName: "באר שבע - אביסרור",
    district: "South",
    openTime: "10:00",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branchId: "13",
    branchName: "בילו סנטר",
    district: "Center",
    openTime: "10:30",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "14",
    branchName: "בית שאן",
    district: "North",
    openTime: "10:30",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "15",
    branchName: "בית שמש",
    district: "Center",
    openTime: "11:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "16",
    branchName: "בני ברק",
    district: "Dan",
    openTime: "10:30",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branchId: "18",
    branchName: "בת ים",
    district: "Dan",
    openTime: "11:00",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branchId: "19",
    branchName: "גבעת שמואל",
    district: "Dan",
    openTime: "09:30",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branchId: "20",
    branchName: "גדרה",
    district: "Center",
    openTime: "10:30",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "21",
    branchName: "קרית אונו",
    district: "Dan",
    openTime: "11:00",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branchId: "22",
    branchName: "בני דרור",
    district: "Dan",
    openTime: "10:30",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branchId: "23",
    branchName: "דלית אל כרמל",
    district: "Haifa",
    openTime: "09:30",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "24",
    branchName: "דימונה",
    district: "South",
    openTime: "10:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "25",
    branchName: "הוד השרון",
    district: "Dan",
    openTime: "09:00",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branchId: "26",
    branchName: "זכרון יעקב",
    district: "Haifa",
    openTime: "09:00",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branchId: "27",
    branchName: "הרצליה",
    district: "Dan",
    openTime: "10:00",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branchId: "28",
    branchName: "חדרה",
    district: "Haifa",
    openTime: "09:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "29",
    branchName: "חולון מזרח",
    district: "Dan",
    openTime: "11:00",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branchId: "30",
    branchName: "חולון מערב",
    district: "Dan",
    openTime: "09:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "31",
    branchName: "חיפה - טכניון",
    district: "Haifa",
    openTime: "10:30",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branchId: "32",
    branchName: "חיפה - מוריה",
    district: "Haifa",
    openTime: "09:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "33",
    branchName: "חיפה - מושבה גרמנית",
    district: "Haifa",
    openTime: "09:00",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branchId: "34",
    branchName: "חריש",
    district: "Haifa",
    openTime: "10:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "35",
    branchName: "טבריה",
    district: "North",
    openTime: "10:30",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branchId: "36",
    branchName: "טייבה",
    district: "Center",
    openTime: "10:00",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branchId: "37",
    branchName: "טירה",
    district: "Center",
    openTime: "09:30",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branchId: "38",
    branchName: "יבנה",
    district: "Center",
    openTime: "09:00",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branchId: "39",
    branchName: "יהוד",
    district: "Center",
    openTime: "11:00",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branchId: "40",
    branchName: "יקנעם",
    district: "Haifa",
    openTime: "10:00",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branchId: "41",
    branchName: "ירושלים - בית הלל",
    district: "Center",
    openTime: "10:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "42",
    branchName: "ירושלים - מלחה",
    district: "Center",
    openTime: "09:30",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "43",
    branchName: "ירושלים - ניות",
    district: "Center",
    openTime: "09:00",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branchId: "44",
    branchName: "ירושלים - פסגת זאב",
    district: "Center",
    openTime: "10:30",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "45",
    branchName: "ירושלים - רמות",
    district: "Center",
    openTime: "11:00",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branchId: "46",
    branchName: "ירושלים - שועפט",
    district: "Center",
    openTime: "10:30",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branchId: "47",
    branchName: "ירושלים - תחנה מרכזית",
    district: "Center",
    openTime: "10:30",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "48",
    branchName: "ירקה",
    district: "North",
    openTime: "09:30",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branchId: "49",
    branchName: "כפר יסעיף",
    district: "North",
    openTime: "09:30",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branchId: "50",
    branchName: "כפר יונה",
    district: "Center",
    openTime: "09:30",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branchId: "51",
    branchName: "כפר מרר",
    district: "North",
    openTime: "11:00",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branchId: "52",
    branchName: "כפר סבא",
    district: "Center",
    openTime: "10:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "53",
    branchName: "כפר קסם",
    district: "Center",
    openTime: "10:30",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "54",
    branchName: "כפר קרע",
    district: "Haifa",
    openTime: "09:00",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branchId: "55",
    branchName: "כרמיאל",
    district: "North",
    openTime: "09:30",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branchId: "56",
    branchName: "כרמיאל - אקספרס",
    district: "North",
    openTime: "09:00",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branchId: "57",
    branchName: "מבשרת ציון",
    district: "Center",
    openTime: "09:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "58",
    branchName: "מגדל",
    district: "North",
    openTime: "10:00",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branchId: "59",
    branchName: "גבעתיים",
    district: "Dan",
    openTime: "10:00",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branchId: "60",
    branchName: "מודיעין",
    district: "Center",
    openTime: "09:00",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branchId: "61",
    branchName: "מעלה אדומים",
    district: "Center",
    openTime: "09:00",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branchId: "61",
    branchName: "מעלות",
    district: "North",
    openTime: "09:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "62",
    branchName: "מצפה רמון",
    district: "South",
    openTime: "10:00",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branchId: "63",
    branchName: "נהריה",
    district: "North",
    openTime: "09:30",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branchId: "64",
    branchName: "נס ציונה",
    district: "Center",
    openTime: "10:30",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branchId: "65",
    branchName: "נצרת",
    district: "Haifa",
    openTime: "09:00",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branchId: "66",
    branchName: "נטיבות",
    district: "South",
    openTime: "11:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "67",
    branchName: "נתניה - מרכז העיר",
    district: "Center",
    openTime: "11:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "68",
    branchName: "נתניה - פולג",
    district: "Center",
    openTime: "10:30",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "69",
    branchName: "סכנין",
    district: "North",
    openTime: "10:00",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branchId: "70",
    branchName: "עכו",
    district: "North",
    openTime: "10:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "71",
    branchName: "עפולה",
    district: "North",
    openTime: "09:30",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branchId: "72",
    branchName: "ערד",
    district: "South",
    openTime: "11:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "73",
    branchName: "פארק אדיסון",
    district: "North",
    openTime: "09:30",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branchId: "74",
    branchName: "רמת גן - מרום נווה",
    district: "Dan",
    openTime: "10:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "75",
    branchName: "רמת גן - קניון ביאליק",
    district: "Dan",
    openTime: "10:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "76",
    branchName: "פרדס חנה",
    district: "Haifa",
    openTime: "10:00",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branchId: "77",
    branchName: "פתח תקווה - אם המושבות",
    district: "Dan",
    openTime: "10:30",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branchId: "78",
    branchName: "פתח תקווה - בלינסון",
    district: "Dan",
    openTime: "11:00",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branchId: "79",
    branchName: "פתח תקווה כפר - גנים",
    district: "Dan",
    openTime: "09:00",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branchId: "80",
    branchName: "פתח תקווה - סירקין",
    district: "Dan",
    openTime: "09:30",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branchId: "81",
    branchName: "קרית מוצקין",
    district: "Haifa",
    openTime: "10:30",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branchId: "82",
    branchName: "קרית אתא",
    district: "Haifa",
    openTime: "10:00",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branchId: "83",
    branchName: "קרית גת",
    district: "South",
    openTime: "10:30",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "82",
    branchName: "ירושלים - קרית יובל",
    district: "Center",
    openTime: "09:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "83",
    branchName: "קרית - שמונה",
    district: "North",
    openTime: "09:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "84",
    branchName: "ראש העין",
    district: "Dan",
    openTime: "10:30",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "85",
    branchName: "ראש פינה",
    district: "North",
    openTime: "10:30",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branchId: "86",
    branchName: "ראשון לציון - מזרח",
    district: "Center",
    openTime: "11:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "87",
    branchName: "ראשון לציון - מערב",
    district: "Center",
    openTime: "10:30",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "88",
    branchName: "רהט",
    district: "South",
    openTime: "10:00",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branchId: "89",
    branchName: "רחובות",
    district: "Center",
    openTime: "11:00",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branchId: "90",
    branchName: "רמת השרון",
    district: "Dan",
    openTime: "10:00",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branchId: "91",
    branchName: "רמלה לוד",
    district: "Center",
    openTime: "10:30",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "92",
    branchName: "רמת ישי",
    district: "Haifa",
    openTime: "09:00",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branchId: "93",
    branchName: "רעננה",
    district: "Center",
    openTime: "10:30",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "94",
    branchName: "שדרות",
    district: "South",
    openTime: "09:30",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branchId: "95",
    branchName: "שוהם",
    district: "Center",
    openTime: "11:00",
    closeTime: "23:00",
    branchOpen: "Open",
  },
  {
    branchId: "96",
    branchName: "שפרעם - קניון האחים סמרה",
    district: "Haifa",
    openTime: "09:30",
    closeTime: "22:30",
    branchOpen: "Open",
  },
  {
    branchId: "97",
    branchName: "תל אביב - יד אליהו",
    district: "Dan",
    openTime: "10:00",
    closeTime: "22:00",
    branchOpen: "Open",
  },
  {
    branchId: "98",
    branchName: "תל אביב - רמת החייל",
    district: "Dan",
    openTime: "09:00",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "99",
    branchName: "תל אביב - חשמונאים",
    district: "Dan",
    openTime: "09:30",
    closeTime: "23:30",
    branchOpen: "Open",
  },
  {
    branchId: "100",
    branchName: "תל אביב - רמת אביב",
    district: "Dan",
    openTime: "09:30",
    closeTime: "22:30",
    branchOpen: "Open",
  },
];

export const pizzaMapId = {
  "אום אל פאחם": "1",
  אופקים: "2",
  "אור עקיבא": "3",
  "אילת - טיילת": "4",
  "איילת -הרים": "5",
  "אילת - קניון אדום": "6",
  אשדוד: "7",
  אשקלון: "8",
  "באקה אל גרבייה": "9",
  "באר שבע - רמות": "10",
  "באר שבע - קניון": "11",
  "באר שבע - אביסרור": "12",
  "בילו סנטר": "13",
  "בית שאן": "14",
  "בית שמש": "15",
  "בני ברק": "16",
  "בת ים": "18",
  "גבעת שמואל": "19",
  גדרה: "20",
  "קרית אונו": "21",
  "בני דרור": "22",
  "דלית אל כרמל": "23",
  דימונה: "24",
  "הוד השרון": "25",
  "זכרון יעקב": "26",
  הרצליה: "27",
  חדרה: "28",
  "חולון מזרח": "29",
  "חולון מערב": "30",
  "חיפה - טכניון": "31",
  "חיפה - מוריה": "32",
  "חיפה - מושבה גרמנית": "33",
  חריש: "34",
  טבריה: "35",
  טייבה: "36",
  טירה: "37",
  יבנה: "38",
  יהוד: "39",
  יקנעם: "40",
  "ירושלים - בית הלל": "41",
  "ירושלים - מלחה": "42",
  "ירושלים - ניות": "43",
  "ירושלים - פסגת זאב": "44",
  "ירושלים - רמות": "45",
  "ירושלים - שועפט": "46",
  "ירושלים - תחנה מרכזית": "47",
  ירקה: "48",
  "כפר יסעיף": "49",
  "כפר יונה": "50",
  "כפר מרר": "51",
  "כפר סבא": "52",
  "כפר קסם": "53",
  "כפר קרע": "54",
  כרמיאל: "55",
  "כרמיאל - אקספרס": "56",
  "מבשרת ציון": "57",
  מגדל: "58",
  גבעתיים: "59",
  מודיעין: "60",
  "מעלה אדומים": "61",
  מעלות: "61",
  "מצפה רמון": "62",
  נהריה: "63",
  "נס ציונה": "64",
  נצרת: "65",
  נטיבות: "66",
  "נתניה - מרכז העיר": "67",
  "נתניה - פולג": "68",
  סכנין: "69",
  עכו: "70",
  עפולה: "71",
  ערד: "72",
  "פארק אדיסון": "73",
  "רמת גן - מרום נווה": "74",
  "רמת גן - קניון ביאליק": "75",
  "פרדס חנה": "76",
  "פתח תקווה - אם המושבות": "77",
  "פתח תקווה - בלינסון": "78",
  "פתח תקווה כפר - גנים": "79",
  "פתח תקווה - סירקין": "80",
  "קרית מוצקין": "81",
  "קרית אתא": "82",
  "קרית גת": "83",
  "ירושלים - קרית יובל": "82",
  "קרית - שמונה": "83",
  "ראש העין": "84",
  "ראש פינה": "85",
  "ראשון לציון - מזרח": "86",
  "ראשון לציון - מערב": "87",
  רהט: "88",
  רחובות: "89",
  "רמת השרון": "90",
  "רמלה לוד": "91",
  "רמת ישי": "92",
  רעננה: "93",
  שדרות: "94",
  שוהם: "95",
  "שפרעם - קניון האחים סמרה": "96",
  "תל אביב - יד אליהו": "97",
  "תל אביב - רמת החייל": "98",
  "תל אביב - חשמונאים": "99",
  "תל אביב - רמת אביב": "100",
};

export const pizzaToppings = [
  "Onions",
  "Olives",
  "Tomato",
  "Corn",
  "Mushrooms",
  "Extra cheese",
  "Pineapple",
  "Papproni",
  "Jalapinios",
  "Hot pepper",
];
